### ISSUE TITLE
Overwrite Existing

### ISSUE THREAD

**Issue by hellfirehd** [zerratar/SubSync#11]
I have a large number of subtitles that are out of sync with their attached video.  It would be nice if I could specify a flag to overwrite them (--overwrite?) so that I can get the latest/greatest versions.

**Comment by zerratar** [comment]
While I think this is a nice idea to completely "resync" more proper "redownload" all subtitles. It does feel like a lot of unnecessary downloads for those that has already been downloaded with SubSync.

This might require a bigger featureset where SubSync remembers previously synced subtitles and if those subtitles still exists it shouldn't redownload them unless forced to. Where the --overwrite would probably be more of a --refresh and --force to force previously downloaded subtitles with subsync to be overwritten. The --refresh would only download subtitles for those that has not been synced using subsync.

But since we don't keep track on whats been synced with SubSync yet, it will have to redownload everything first time after this feature has been added.

But regardless, I like it. And I will see If i can add this.
Thanks for your suggestion!

**Comment by zerratar** [comment]
I've added two new arguments:

`--resync - download new and overwrite all existing subtitles that has not been flagged by SubSync as 'synchronized'`

`--resyncall - download new and overwrite all existing subtitles, even if subsync has previously synced them.`

This is not tested yet properly so if you find any issues with it, please let me know!

**Comment by hellfirehd** [comment]
This is awesome!  Do you even sleep?
